# Generated by Django 3.1.3 on 2020-12-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pets', '0005_auto_20201208_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.AddField(
            model_name='pet',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
